# Generated by Django 5.1.1 on 2024-09-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JIRAFIELD',
            fields=[
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('field_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('schema_json', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('field_key', models.CharField(blank=True, max_length=255, null=True)),
                ('stable_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('searcherKey', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
