# Generated by Django 5.1.1 on 2024-09-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiradata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GetsiteFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=1000)),
            ],
        ),
    ]
