# Generated by Django 5.1.1 on 2024-09-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiradata', '0002_checkstatistics_getsitefields'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type_id', models.CharField(max_length=1000)),
                ('issue_type_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('issue_json', models.JSONField()),
            ],
        ),
    ]
