# Generated by Django 5.1.1 on 2024-09-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiradata', '0003_issuetypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuetypes',
            name='issue_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
